#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      brew install sysdig
      ;;
    *)
      curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash
      ;;
  esac
}

main "$@"
