#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_sysdig="$(sysdig --version 2>/dev/null | awk '{print $3}' || true)"
  jq -n --arg sysdig "$ver_sysdig" '{sysdig: $sysdig}'
}

version "$@"
