#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_sysdig="0.0.1"
  jq -n --arg sysdig "$ver_sysdig" '{sysdig: $sysdig}'
}

version "$@"
